# -*- coding: utf-8 -*-
"""api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/160h402OatFL0q1FnlDcJFtMB4lhZ3Em8
"""

import joblib
import numpy as np
from flask import Flask, request, jsonify

app = Flask(__name__)

# Load models
stream_model = joblib.load("stream_model.pkl")
admission_model = joblib.load("admission_model.pkl")
scaler = joblib.load("scaler.pkl")

@app.route("/")
def home():
    return "ML Career Advisor API is running!"

@app.route("/predict_stream", methods=["POST"])
def predict_stream():
    data = request.json
    features = np.array([[
        data["quantitative_score"],
        data["logical_score"],
        data["verbal_score"],
        data["creative_score"],
        data["technical_score"]
    ]])

    prediction = stream_model.predict(features)[0]
    return jsonify({"recommended_stream": prediction})

@app.route("/predict_admission", methods=["POST"])
def predict_admission():
    data = request.json
    features = np.array([[data["aggregate_percentage"], data["score_cutoff_difference"]]])
    features_scaled = scaler.transform(features)

    prediction = admission_model.predict(features_scaled)[0]
    return jsonify({"admission_chance": int(prediction)})

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=10000)
