# -*- coding: utf-8 -*-
"""K1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ITPgwh7c4Iedv1VJehkC2eFXnCjDLqcG

##### ***One-Stop Personalized Career & Education Advisor for Students***

Our platform offers personalized career and education guidance for post-10th/12th students. It uses aptitude testing, course-to-career mapping, and a government college directory with AI recommendations to help students make informed academic choices.
"""

from google.colab import drive
drive.mount('/content/drive')

"""Imports"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""### Data Exploration"""

# We have two datasets
## Colleges Dataset
## Students Dataset

# Read
college_data = pd.read_csv(
    "/content/SIH25094_colleges_dataset_1.csv"

)
student_data = pd.read_csv(
    "/content/SIH25094_students_with_college (1).csv"
)

# Features
print("College Data Columns: ")
print(college_data.columns)

print("\n")
print("Student Data Columns: ")
print(student_data.columns)

# The two datasets can be merged using these two columns
# - 'college_id' & 'assigned_college_id'
print(college_data['college_id'].head(4))
print("---"*60)
print(student_data['assigned_college_id'].head(4))

# Shapes
print("Shapes before merging: ")
print(f"College Data Shape: {college_data.shape}")
print(f"Student Data Shape: {student_data.shape}")

import pandas as pd
# Thus, These two columns can be used to connect both the datasets
merged_df = pd.merge(
    left = student_data,
    right = college_data,
    left_on = 'assigned_college_id',
    right_on = 'college_id',
    how = 'left'
)
print("Shapes after merging: ")
print(f"Merged Data Shape: {merged_df.shape}")
display(merged_df.head())

print("After Merge Shape: ")
print(f"Merged Data Shape: {merged_df.shape}")

print("After Merge Shape:")
print(f"Merged Data Shape: {merged_df.shape}")

print("\nPreview of Merged Dataset:")
display(merged_df.sample(10))

# Save merged dataset as CSV
merged_df.to_csv('/content/merged_dataset.csv', index=False)

print("File saved successfully!")

from google.colab import files
files.download('/content/merged_dataset.csv')

if 'merged_df' not in locals() and 'merged_df' not in globals():
    # Re-create merged_df if it's not defined (e.g., after kernel restart or partial execution)
    if 'student_data' in locals() and 'college_data' in locals():
        merged_df = pd.merge(
            left = student_data,
            right = college_data,
            left_on = 'assigned_college_id',
            right_on = 'college_id',
            how = 'left'
        )
        print("Recreated 'merged_df' for saving.")
    else:
        print("Error: 'student_data' or 'college_data' not found to recreate 'merged_df'.")
        # You might want to raise an error or handle this case differently

# Save merged dataset as CSV
merged_df.to_csv('/content/merged_dataset.csv', index=False)

print("File saved successfully!")

# Let's check for any students whose assigned_college_id was not found in college data
null_val = merged_df['college_name'].isnull().sum()
print(f"Number of students with no matching college found: {null_val}")

merged_df.drop("college_id", axis=1, inplace=True)

# Final cols
print(merged_df.columns)

"""### Data Cleaning"""

df = merged_df

"""Handling Null Values"""

# Check for null values
df.isnull().sum()[df.isnull().sum() > 0]

"""We have to handle these null values as such -
1. device_access: The best approach is to create a new category 'unknown' instead of guessing the mode.
2. extracurricular: It is null possibly because students who do not have opted for it simply left it blank. Thus, we can fill it with 'None'
3. admission_year_predicted: This has a lot of null values and this feature is not reliable enough for analysis or training the model. So, we will drop the entire column.
4. scholarships_available: It is null possibly because the college doesn't has scholarships. So, we can fill it with 'None', assuming it doesn't have any scholarship.
"""

df['device_access'].fillna('Unknown', inplace=True)
df['extracurricular'].fillna('None', inplace=True)
df['scholarships_available'].fillna('None', inplace=True)
df.drop(columns=['admission_year_predicted'], axis=1, inplace=True, errors='ignore')

# List of critical numerical columns for all models that might have NaNs
critical_numerical_cols = [
    'quantitative_score', 'logical_score', 'verbal_score', 'creative_score',
    'technical_score', 'aggregate_percentage', 'last_year_cutoff',
    'dropout_risk_score'
]

# Convert these columns to numeric, coercing errors to NaN
# This ensures that any non-numeric missing values (like 'None' or empty strings) become actual np.nan
for col in critical_numerical_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Drop rows where any of these critical numerical columns have NaNs
# This should effectively remove the problematic row(s) early in the cleaning process
initial_rows = df.shape[0]
df.dropna(subset=critical_numerical_cols, inplace=True)
rows_after_drop = df.shape[0]
print(f"Dropped {initial_rows - rows_after_drop} rows due to NaNs in critical numerical columns.")

print(
    f"Null values in DF: {df.isna().sum().sum()}"
)

"""Checking for Duplicates"""

# Full Duplicates: Where the whole rows are identical
fd_count = df.duplicated().sum()
print(f"Found {fd_count} fully duplicated rows in data.")

# Duplicate Student ID
sd_count = df.duplicated(subset=['student_id']).sum()
print(f"Found {sd_count} records with duplicate student ids.")

merged_df = df

"""### Exploratory Data Analysis

##### 1. Univariate Analysis
The goal here is to understand the fundamental distributions of our key features one by one.
"""

# Set a consistent style for all our plots
sns.set_style("whitegrid")

# 1. Student Performance: Distribution of Aggregate percentage
print("Student Performance Analysis: ")
plt.figure(figsize=(12, 6))
sns.histplot(merged_df['aggregate_percentage'], kde=True, bins=40, color='blue')
plt.title('Distribution of Student Aggregate Percentage', fontsize=16)
plt.xlabel('Aggregate Percentage', fontsize=12)
plt.ylabel('Number of Students', fontsize=12)
plt.axvline(merged_df['aggregate_percentage'].mean(), color='red', linestyle='--', label=f"Mean: {merged_df['aggregate_percentage'].mean():.2f}")
plt.axvline(merged_df['aggregate_percentage'].median(), color='green', linestyle='-', label=f"Median: {merged_df['aggregate_percentage'].median():.2f}")
plt.legend()
plt.show()

# 2. College Selectivity: Distribution of Last Year Cutoff
print("\n--- 2. Analyzing College Selectivity ---")
plt.figure(figsize=(12, 6))
sns.histplot(merged_df['last_year_cutoff'], kde=True, bins=40, color='purple')
plt.title('Distribution of College Last Year Cutoff', fontsize=16)
plt.xlabel('Last Year Cutoff Percentage', fontsize=12)
plt.ylabel('Frequency', fontsize=12)
plt.axvline(merged_df['last_year_cutoff'].mean(), color='red', linestyle='--', label=f"Mean: {merged_df['last_year_cutoff'].mean():.2f}")
plt.axvline(merged_df['last_year_cutoff'].median(), color='green', linestyle='-', label=f"Median: {merged_df['last_year_cutoff'].median():.2f}")
plt.legend()
plt.show()

# 3. Student Demographics: State and Socio-Economic Status
print("\n--- 3. Analyzing Student Demographics ---")
# Bar chart for the top 15 student states
plt.figure(figsize=(12, 8))
top_15_states = merged_df['state'].value_counts().nlargest(15)
sns.barplot(x=top_15_states.values, y=top_15_states.index, palette='viridis')
plt.title('Top 15 States by Number of Students', fontsize=16)
plt.xlabel('Number of Students', fontsize=12)
plt.ylabel('State', fontsize=12)
plt.show()

# Bar chart for socio-economic status
plt.figure(figsize=(12, 6))
sns.countplot(y=merged_df['socio_economic_status'], order=merged_df['socio_economic_status'].value_counts().index, palette='plasma')
plt.title('Distribution of Students by Socio-Economic Status', fontsize=16)
plt.xlabel('Number of Students', fontsize=12)
plt.ylabel('Socio-Economic Status', fontsize=12)
plt.show()

# 4. Stream Popularity: Distribution of Suggested Streams
print("\n--- 4. Analyzing Stream Popularity ---")
plt.figure(figsize=(12, 6))
sns.countplot(y=merged_df['suggested_stream'], order=merged_df['suggested_stream'].value_counts().index, palette='magma')
plt.title('Distribution of Suggested Streams for Students', fontsize=16)
plt.xlabel('Number of Students', fontsize=12)
plt.ylabel('Suggested Stream', fontsize=12)
plt.show()

"""1. Student Aggregate Percentage
Analysis: A perfect bell curve. This means the student performance data is balanced, healthy, and ideal for machine learning.
2. College Last Year Cutoff
Analysis: The distribution has multiple peaks, indicating there are different "tiers" of colleges (e.g., easy, moderate, hard to get into). The average cutoff is higher than the average student score, highlighting the competitive landscape.
3. Top 15 States by Number of Students
Analysis: The student population is geographically diverse and not concentrated in one region.
4. Distribution by Socio-Economic Status
Analysis: The dataset is heavily skewed towards students from lower and middle-income backgrounds.
5. Distribution of Suggested Streams
Analysis: Science and Commerce are the dominant recommendations. This means the stream data is imbalanced.

##### 2. Bivariate Analysis
Here we look for relationships between pairs.
"""

# --- 1. Aptitude vs. Suggested Stream ---
# We'll check if quantitative scores are higher for Science streams as expected.
plt.figure(figsize=(12, 7))
sns.boxplot(x='quantitative_score', y='suggested_stream', data=merged_df, palette='viridis')
plt.title('Quantitative Score Distribution by Suggested Stream', fontsize=16)
plt.xlabel('Quantitative Score', fontsize=12)
plt.ylabel('Suggested Stream', fontsize=12)
plt.show()

# --- 2. Student Score vs. College Cutoff ---
# We expect most students to be above the y=x line, meaning their score > cutoff.
plt.figure(figsize=(10, 8))
sns.scatterplot(x='last_year_cutoff', y='aggregate_percentage', data=merged_df, alpha=0.5)
# Add a reference line where score equals cutoff
plt.plot([40, 100], [40, 100], color='red', linestyle='--', label='Cutoff Line (Score = Cutoff)')
plt.title('Student Percentage vs. College Cutoff', fontsize=16)
plt.xlabel('College Last Year Cutoff', fontsize=12)
plt.ylabel('Student Aggregate Percentage', fontsize=12)
plt.legend()
plt.show()

# --- 3. Dropout Risk by Socio-Economic Status ---
# To investigate if dropout risk is related to student's background
plt.figure(figsize=(12, 7))
sns.boxplot(x='dropout_risk_score', y='socio_economic_status', data=merged_df, palette='plasma')
plt.title('Dropout Risk Score by Socio-Economic Status', fontsize=16)
plt.xlabel('Dropout Risk Score', fontsize=12)
plt.ylabel('Socio-Economic Status', fontsize=12)
plt.show()

"""1. Aptitude vs. Stream
Analysis: The plot confirms your data is logical. Science students have the highest quantitative scores.
2. Student Score vs. College Cutoff
Analysis: Many students have scores below their assigned college's cutoff. This means admission depends on more than just marks.
3. Dropout Risk vs. Socio-Economic Status
Analysis: Dropout risk is the same across all economic classes. This means income status alone is not the cause.

##### 3. Feature Engineering
To create features critical for the model
"""

# --- 1. Feature Engineering: Create Score vs. Cutoff Difference ---

print("Creating the 'score_cutoff_difference' feature...")

merged_df['score_cutoff_difference'] = merged_df['aggregate_percentage'] - merged_df['last_year_cutoff']

# Display the first few rows with the new column to verify
print("Verification: First 5 rows with the new feature:")
print(merged_df[['student_id', 'aggregate_percentage', 'last_year_cutoff', 'score_cutoff_difference']].head())

# Display a quick summary of the new feature
print("\nSummary of the new 'score_cutoff_difference' feature:")
print(merged_df['score_cutoff_difference'].describe())

"""##### 4. Multivariate Analysis
Create a heatmap to see the relationships between all key numerical variables at once
"""

# --- 2. Multivariate Analysis: Correlation Heatmap ---

# Select only the most relevant numerical columns for the heatmap
numerical_features = [
    'quantitative_score', 'logical_score', 'verbal_score', 'creative_score',
    'technical_score', 'aggregate_percentage', 'last_year_cutoff',
    'dropout_risk_score', 'score_cutoff_difference' # Including our new feature
]

# Calculate the correlation matrix
correlation_matrix = merged_df[numerical_features].corr()

# Create the heatmap
plt.figure(figsize=(14, 10))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=.5)
plt.title('Correlation Heatmap of Key Numerical Features', fontsize=16)
plt.show()

"""Observations:
- The student's academic score goes up, their risk of dropping out goes down.
- Our feature perfectly captures relation between student's performance and their college's selectivity.

##### 5. Data Processing for ML
We will prepare the data specifically for our first model: the Dropout Risk Prediction Model. The goal is to predict which students are at a high risk of dropping out.
"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Define the features (X) we will use for prediction
feature_columns = [
    'aggregate_percentage',
    'score_cutoff_difference', # Our powerful engineered feature
    'socio_economic_status',
    'parental_education',
    'school_type',
    'internet_access',
    'device_access',
    'quantitative_score',
    'logical_score',
    'verbal_score'
]

# Define the target (y) we want to predict
target_column = 'dropout_risk_score'

# Create a new, smaller DataFrame for this specific model
model_df = merged_df[feature_columns + [target_column]].copy()

# Recreate model_df to ensure target_column is present in case of re-execution
model_df = merged_df[feature_columns + [target_column]].copy()

print("--- 2. Creating Binary Target Variable 'high_dropout_risk' ---")
risk_threshold = 70
model_df['high_dropout_risk'] = (model_df[target_column] > risk_threshold).astype(int)

# Drop the original score column as we now have our target
model_df.drop(target_column, axis=1, inplace=True)

# Remove any rows with NaN values after creating the target variable
model_df.dropna(inplace=True)

# Display the class balance
print(f"Risk Threshold set at: {risk_threshold}")
print("Distribution of target variable:")
print(model_df['high_dropout_risk'].value_counts(normalize=True))

# We convert all text-based columns into a numerical format.

print("\n--- 3. Encoding Categorical Features ---")

# Identify which columns are categorical
categorical_features = model_df.select_dtypes(include=['object']).columns

# Use pandas.get_dummies for one-hot encoding
model_df_encoded = pd.get_dummies(model_df, columns=categorical_features, drop_first=True)

print("Data has been successfully encoded.")
print(f"Original number of features: {len(feature_columns)}")
print(f"Number of features after encoding: {len(model_df_encoded.columns) - 1}") # -1 for the target column

# Separate the features (X) from the target (y)

X = model_df_encoded.drop('high_dropout_risk', axis=1)
y = model_df_encoded['high_dropout_risk']

print("\n--- 4. Final X (features) and y (target) are ready for model training ---")
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

# We'll use an 80/20 split. 80% for training, 20% for testing.
# `random_state` ensures that we get the same split every time we run the code.
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y  # 'stratify=y' ensures the proportion of high/low risk students is the same in both train and test sets.
)

print("--- Data Splitting Complete ---")
print("Shape of X_train:", X_train.shape)
print("Shape of y_train:", y_train.shape)
print("---")
print("Shape of X_test:", X_test.shape)
print("Shape of y_test:", y_test.shape)

"""##### 6. Model training

"""

# Import the models and evaluation metrics
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from lightgbm import LGBMClassifier
from sklearn.metrics import classification_report, accuracy_score
from sklearn.preprocessing import StandardScaler

# It's a best practice to scale numerical features for these models.

# --- NEW: Explicit NaN check and removal before scaling ---
print("\n--- Performing final NaN check before scaling ---")
if X_train.isnull().sum().sum() > 0:
    print(f"Warning: Found {X_train.isnull().sum().sum()} NaNs in X_train. Dropping rows with NaNs.")
    # Drop NaNs from X_train and corresponding y_train
    nan_rows_train = X_train.isnull().any(axis=1)
    X_train = X_train[~nan_rows_train]
    y_train = y_train[~nan_rows_train]
    print(f"X_train shape after dropping NaNs: {X_train.shape}")
    print(f"y_train shape after dropping NaNs: {y_train.shape}")

if X_test.isnull().sum().sum() > 0:
    print(f"Warning: Found {X_test.isnull().sum().sum()} NaNs in X_test. Dropping rows with NaNs.")
    # Drop NaNs from X_test and corresponding y_test
    nan_rows_test = X_test.isnull().any(axis=1)
    X_test = X_test[~nan_rows_test]
    y_test = y_test[~nan_rows_test]
    print(f"X_test shape after dropping NaNs: {X_test.shape}")
    print(f"y_test shape after dropping NaNs: {y_test.shape}")
else:
    print("No NaNs found in X_train or X_test.")


scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

"""**Models**

In this project, we have two main models:

1.  **The Dropout Risk Prediction Model (which we just built).**
    *   **Input:** Student academic and demographic data.
    *   **Output:** A prediction (Yes/No) if the student is at high risk of dropping out.
    *   **Purpose:** Powers proactive student tracking system (Outcome 4).

2.  **The Stream Recommendation Model (which we will build next).**
    *   **Input:** Student's aptitude quiz scores.
    *   **Output:** A prediction of the most suitable stream (Science, Commerce, Arts, etc.).
    *   **Purpose:** Powers personalized career guidance system (Outcome 1).

###### a. Dropout Risk Prediction Model
"""

# Define the models we want to evaluate
models = {
    "Logistic Regression": LogisticRegression(random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42),
    "LightGBM": LGBMClassifier(random_state=42)
}

# Loop through each model to train, predict, and evaluate
for model_name, model in models.items():

    # Train the model
    print(f"--- Training {model_name} ---")
    model.fit(X_train_scaled, y_train)
    print("Training complete.")

    # Make predictions on the test set
    y_pred = model.predict(X_test_scaled)

    # Evaluate the model
    print(f"\n--- Evaluation for {model_name} ---")

    # Calculate accuracy
    accuracy = accuracy_score(y_test, y_pred)
    print(f"Accuracy: {accuracy:.4f}")

    # Print the detailed classification report
    # This shows precision, recall, and f1-score for each class (0 and 1)
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred, target_names=["Not High Risk (0)", "High Risk (1)"]))
    print("----------------------------------------------------\n")

"""**Model Analysis and Selection**
1. **Logistic Regression**:
- This was a decent baseline, but its Recall (0.52) for high-risk students is too low. This means it failed to identify almost half of the students who are actually at risk, which is a critical failure for our project's goal.

2. **Random Forest & LightGBM**:
- These two models performed identically and exceptionally well.
- They both achieved a high F1-Score (0.79) for the "High Risk" class, which is a strong indicator of a balanced and effective model.
- Their Recall (0.77) means they successfully identified 77% of the students who were truly at risk, a huge improvement over Logistic Regression.
- Their Precision (0.82) means that when they flag a student, they are correct 82% of the time.

Thus, We will select **Random Forest** model for Dropout Risk Prediction!

###### b. Stream Recommendation Model
"""

# The features (X) are the student's aptitude scores
feature_columns = [
    'quantitative_score',
    'logical_score',
    'verbal_score',
    'creative_score',
    'technical_score'
]

# The target (y) is the stream we want to predict
target_column = 'suggested_stream'

# Create the feature matrix X and the target vector y
X = merged_df[feature_columns]
y = merged_df[target_column]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\n--- Data Splitting Complete ---")
print("Shape of X_train:", X_train.shape)
print("Shape of y_train:", y_train.shape)
print("---")
print("Shape of X_test:", X_test.shape)
print("Shape of y_test:", y_test.shape)

"""Models"""

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from lightgbm import LGBMClassifier
from sklearn.metrics import classification_report, accuracy_score

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

models = {
    "Logistic Regression": LogisticRegression(random_state=42, max_iter=1000), # Increased max_iter for convergence
    "Random Forest": RandomForestClassifier(random_state=42),
    "LightGBM": LGBMClassifier(random_state=42)
}

# Loop through each model to train, predict, and evaluate
for model_name, model in models.items():

    # Train the model
    print(f"--- Training {model_name} ---")
    model.fit(X_train_scaled, y_train)
    print("Training complete.")

    # Make predictions on the test set
    y_pred = model.predict(X_test_scaled)

    # Evaluate the model
    print(f"\n--- Evaluation for {model_name} ---")

    # Calculate overall accuracy
    accuracy = accuracy_score(y_test, y_pred)
    print(f"Overall Accuracy: {accuracy:.4f}")

    # Print the detailed classification report
    # This is crucial as it shows the performance for each individual stream
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))
    print("----------------------------------------------------\n")

"""**Final Analysis**

*   **Best Models:** LightGBM and Random Forest were the clear winners, performing much better than the basic model.

*   **Excellent on Major Streams:** The models are highly accurate at recommending the main streams: **Science, Commerce, and Humanities.**

*   **Known Limitation:** The models are less accurate for smaller, less common streams like "Mixed" due to limited data.

*   **Final Choice:** **LightGBM is the selected model.** It has the best overall performance and will reliably guide the majority of students.

---

#### **College Recommendation**
"""

# --- Chapter 3: Building the Admission Prediction Model (Final Version) ---

# --- Step 1: Feature Selection and Target Definition ---

print("--- Preparing Data for the Admission Prediction Model ---")

# Define the features (X) that will be used to predict admission
feature_columns = [
    'aggregate_percentage',
    'score_cutoff_difference', # We can use this powerful feature again
    'socio_economic_status',
    'school_type',
    'parental_education',
    'extracurricular',
    'state',
    'college_state'
]

target_column = 'admission_status_current'

# --- Step 2: Filter for Finalized Admission Outcomes ---
# We will train our model on students who were either 'Accepted' or 'Waitlisted'.
# We treat 'Waitlisted' as a negative outcome (not accepted).
valid_statuses = ['Accepted', 'Waitlisted']
model_df_admission = merged_df[merged_df[target_column].isin(valid_statuses)].copy()

# Safeguard check
if model_df_admission.empty:
    raise ValueError("The DataFrame is empty. No 'Accepted' or 'Waitlisted' statuses found.")
else:
    print(f"Found {len(model_df_admission)} rows with finalized admission statuses.")

# --- Step 3: Create a Binary Target Variable ---
print("\n--- Creating Binary Target 'is_accepted' ---")
# Convert the status into a 1/0 format. 1 for 'Accepted', 0 for 'Waitlisted'.
model_df_admission['is_accepted'] = model_df_admission[target_column].apply(lambda x: 1 if x == 'Accepted' else 0)

# Display the class balance
print("Distribution of Target Variable:")
print(model_df_admission['is_accepted'].value_counts(normalize=True))

# --- Step 4: Select Final Data, Encode, and Split ---
print("\n--- Encoding and Splitting the Data ---")
# Select only the columns we need
final_df = model_df_admission[feature_columns + ['is_accepted']]
# Handle any potential missing values in our chosen columns
final_df.dropna(inplace=True)

categorical_features = final_df.select_dtypes(include=['object']).columns
final_df_encoded = pd.get_dummies(final_df, columns=categorical_features, drop_first=True)

X = final_df_encoded.drop('is_accepted', axis=1)
y = final_df_encoded['is_accepted']

X_train_adm, X_test_adm, y_train_adm, y_test_adm = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nData preparation for the Admission Prediction Model is complete.")
print("Shape of X_train:", X_train_adm.shape)
print("Shape of y_test:", y_test_adm.shape)

# Import the models and evaluation metrics
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from lightgbm import LGBMClassifier
from sklearn.metrics import classification_report, accuracy_score
from sklearn.preprocessing import StandardScaler

print("--- Preparing Data for a PURE Aptitude-Based Stream Recommender ---")

# The features (X) are ONLY the student's aptitude scores
feature_columns_stream = [
    'quantitative_score',
    'logical_score',
    'verbal_score',
    'creative_score',
    'technical_score'
]
target_column_stream = 'suggested_stream'

# Create the specific X and y for this model
X_stream = merged_df[feature_columns_stream]
y_stream = merged_df[target_column_stream]

# Create new, specific train/test splits for this model
X_train_stream, X_test_stream, y_train_stream, y_test_stream = train_test_split(
    X_stream,
    y_stream,
    test_size=0.20,
    random_state=42,
    stratify=y_stream
)

print("Data splitting complete. Training models on ONLY 5 aptitude features.")

# Define the models
models_stream = {
    "Random Forest": RandomForestClassifier(random_state=42),
    "LightGBM": LGBMClassifier(random_state=42)
}

# Loop through and train
for model_name, model in models_stream.items():
    print(f"\n--- Training {model_name} for Stream Recommendation ---")
    model.fit(X_train_stream, y_train_stream)
    y_pred_stream = model.predict(X_test_stream)

    print(f"--- Evaluation for {model_name} ---")
    print(f"Overall Accuracy: {accuracy_score(y_test_stream, y_pred_stream):.4f}")
    print("\nClassification Report:")
    print(classification_report(y_test_stream, y_pred_stream))
    print("----------------------------------------------------\n")

# **IMPORTANT**: Assign the best performing model to a new, clear variable name
stream_recommender_model = models_stream["LightGBM"]
print("Final Stream Recommender Model (LightGBM) is now correctly trained on 5 features.")

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

# --- Final Step: Building the Holistic Recommendation Engine (Corrected) ---

# Re-assign your best models for clarity
stream_recommender_model = models_stream["LightGBM"] # From stream model training. Corrected to models_stream
admission_predictor_model = models["Random Forest"] # From admission model training. Corrected to Random Forest as it was better

# Create and fit a scaler specifically for the admission model data
scaler_adm = StandardScaler()
X_train_adm_scaled = scaler_adm.fit_transform(X_train_adm)
# Note: X_test_adm is not directly used here, but the scaler needs to be fitted.

def get_college_recommendations(student_profile, stream_model, admission_model, scaler, train_cols, all_colleges_df, top_n=5):
    """
    Generates a ranked list of the top N most suitable colleges for a student.
    ... (docstring remains the same)
    """

    print("---> Starting Recommendation Process ---")

    # --- Stage 1: Predict the Student's Best Stream ---
    # **CORRECTION IS HERE**: We define the list of columns correctly.
    aptitude_features = ['quantitative_score', 'logical_score', 'verbal_score', 'creative_score', 'technical_score']

    # We now select the data correctly, ensuring it's in the right format for the model
    student_aptitudes = student_profile[aptitude_features].values.reshape(1, -1)



    # Create a new scaler for stream prediction and fit it (assuming it's needed here as it was in stream training)
    stream_scaler = StandardScaler()
    stream_scaler.fit(X_stream) # X_stream is the full aptitude data used for stream model training
    student_aptitudes_scaled_for_stream = stream_scaler.transform(student_aptitudes)

    predicted_stream = stream_model.predict(student_aptitudes_scaled_for_stream)[0]
    print(f"1. Predicted Best Stream: {predicted_stream}")

    # --- Stage 2: Filter Colleges to Create a Candidate Pool ---
    candidate_colleges = all_colleges_df[all_colleges_df['stream_offered'].str.contains(predicted_stream, case=False, na=False)].copy()
    print(f"2. Found {len(candidate_colleges)} candidate colleges for this stream.")

    if candidate_colleges.empty:
        print("No colleges found for the predicted stream. Recommendation process stopped.")
        return []

    # --- Stage 3: Score and Rank Each Candidate College ---
    # (The rest of the function remains exactly the same)
    recommendations = []
    print("3. Scoring each candidate college...")

    for index, college in candidate_colleges.iterrows():
        prediction_data = student_profile.copy()
        prediction_data['college_state'] = college['college_state']
        prediction_data['last_year_cutoff'] = college['last_year_cutoff']
        prediction_data['score_cutoff_difference'] = prediction_data['aggregate_percentage'] - college['last_year_cutoff']

        single_row_df = pd.DataFrame([prediction_data.loc[admission_model_features]]) # Use .loc for Series indexing with list
        single_row_encoded = pd.get_dummies(single_row_df)
        single_row_aligned = single_row_encoded.reindex(columns=train_cols, fill_value=0)
        single_row_scaled = scaler.transform(single_row_aligned) # This `scaler` is `scaler_adm`

        admission_prob = admission_model.predict_proba(single_row_scaled)[0][1]
        academic_fit_score = admission_prob

        location_fit = 1.0 if student_profile['state'] == college['college_state'] else 0.5

        pref_fit = 0
        if student_profile['prefers_government_college'] == 'Yes' and 'Government' in college['college_type']:
            pref_fit = 1.0
        elif student_profile['prefers_government_college'] == 'No' and 'Private' in college['college_type']:
            pref_fit = 1.0

        personal_fit_score = np.mean([location_fit, pref_fit])

        final_score = (0.7 * academic_fit_score) + (0.3 * personal_fit_score)

        recommendations.append((college['college_name'], final_score))

    # --- Stage 4: Return the Top N Recommendations ---
    recommendations.sort(key=lambda x: x[1], reverse=True)

    print("\n--- Recommendation Process Complete ---")
    return recommendations[:top_n]


# --- DEMONSTRATION: HOW TO USE THE ENGINE ---

# 1. Create a sample student profile
sample_student = pd.Series({
    'quantitative_score': 85,
    'logical_score': 82,
    'verbal_score': 70,
    'creative_score': 65,
    'technical_score': 40,
    'aggregate_percentage': 88.0,
    'socio_economic_status': 'Middle',
    'school_type': 'Private',
    'parental_education': 'Graduate',
    'extracurricular': 'Sports',
    'state': 'Maharashtra',
    'prefers_government_college': 'Yes'
})

# 2. Define the feature list used for the admission model
admission_model_features = [
    'aggregate_percentage', 'score_cutoff_difference', 'socio_economic_status',
    'school_type', 'parental_education', 'extracurricular', 'state', 'college_state'
]

# Define college_df (from previous cells)
college_df = college_data.copy() # Ensure college_df is defined from the loaded data

# Corrected: Select the best models based on earlier evaluation
# stream_recommender_model was LightGBM for stream.
# admission_predictor_model was Random Forest for dropout (acting as admission here).
stream_recommender_model = models_stream["LightGBM"] # Re-confirming best stream model
admission_predictor_model = RandomForestClassifier(random_state=42).fit(X_train_adm_scaled, y_train_adm) # Re-instantiate and fit the best admission model


# 3. Run the engine!
top_colleges = get_college_recommendations(
    student_profile=sample_student,
    stream_model=stream_recommender_model,
    admission_model=admission_predictor_model,
    scaler=scaler_adm, # Now scaler_adm is defined
    train_cols=X_train_adm.columns,
    all_colleges_df=college_df,
    top_n=5
)

# 4. Print the final output
print("\nTop 5 Recommended Colleges for the Student:")
for i, (college, score) in enumerate(top_colleges, 1):
    print(f"{i}. {college} (Suitability Score: {score:.2f})")

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

# --- Final Step: Building the Holistic Recommendation Engine (Corrected) ---

# Re-assign your best models for clarity
stream_recommender_model = models_stream["LightGBM"] # From stream model training. Corrected to models_stream
admission_predictor_model = models["Random Forest"] # From admission model training. Corrected to Random Forest as it was better

# Create and fit a scaler specifically for the admission model data
scaler_adm = StandardScaler()
X_train_adm_scaled = scaler_adm.fit_transform(X_train_adm)
# Note: X_test_adm is not directly used here, but the scaler needs to be fitted.

def get_college_recommendations(student_profile, stream_model, admission_model, scaler, train_cols, all_colleges_df, top_n=5):
    """
    Generates a ranked list of the top N most suitable colleges for a student.
    ... (docstring remains the same)
    """

    print("---> Starting Recommendation Process ---")

    # --- Stage 1: Predict the Student's Best Stream ---
    # **CORRECTION IS HERE**: We define the list of columns correctly.
    aptitude_features = ['quantitative_score', 'logical_score', 'verbal_score', 'creative_score', 'technical_score']

    # We now select the data correctly, ensuring it's in the right format for the model
    student_aptitudes = student_profile[aptitude_features].values.reshape(1, -1)



    # Create a new scaler for stream prediction and fit it (assuming it's needed here as it was in stream training)
    stream_scaler = StandardScaler()
    stream_scaler.fit(X_stream) # X_stream is the full aptitude data used for stream model training
    student_aptitudes_scaled_for_stream = stream_scaler.transform(student_aptitudes)

    predicted_stream = stream_model.predict(student_aptitudes_scaled_for_stream)[0]
    print(f"1. Predicted Best Stream: {predicted_stream}")

    # --- Stage 2: Filter Colleges to Create a Candidate Pool ---
    candidate_colleges = all_colleges_df[all_colleges_df['stream_offered'].str.contains(predicted_stream, case=False, na=False)].copy()
    print(f"2. Found {len(candidate_colleges)} candidate colleges for this stream.")

    if candidate_colleges.empty:
        print("No colleges found for the predicted stream. Recommendation process stopped.")
        return []

    # --- Stage 3: Score and Rank Each Candidate College ---
    # (The rest of the function remains exactly the same)
    recommendations = []
    print("3. Scoring each candidate college...")

    for index, college in candidate_colleges.iterrows():
        prediction_data = student_profile.copy()
        prediction_data['college_state'] = college['college_state']
        prediction_data['last_year_cutoff'] = college['last_year_cutoff']
        prediction_data['score_cutoff_difference'] = prediction_data['aggregate_percentage'] - college['last_year_cutoff']

        single_row_df = pd.DataFrame([prediction_data.loc[admission_model_features]]) # Use .loc for Series indexing with list
        single_row_encoded = pd.get_dummies(single_row_df)
        single_row_aligned = single_row_encoded.reindex(columns=train_cols, fill_value=0)
        single_row_scaled = scaler.transform(single_row_aligned) # This `scaler` is `scaler_adm`

        admission_prob = admission_model.predict_proba(single_row_scaled)[0][1]
        academic_fit_score = admission_prob

        location_fit = 1.0 if student_profile['state'] == college['college_state'] else 0.5

        pref_fit = 0
        if student_profile['prefers_government_college'] == 'Yes' and 'Government' in college['college_type']:
            pref_fit = 1.0
        elif student_profile['prefers_government_college'] == 'No' and 'Private' in college['college_type']:
            pref_fit = 1.0

        personal_fit_score = np.mean([location_fit, pref_fit])

        final_score = (0.7 * academic_fit_score) + (0.3 * personal_fit_score)

        recommendations.append((college['college_name'], final_score))

    # --- Stage 4: Return the Top N Recommendations ---
    recommendations.sort(key=lambda x: x[1], reverse=True)

    print("\n--- Recommendation Process Complete ---")
    return recommendations[:top_n]


# --- DEMONSTRATION: HOW TO USE THE ENGINE ---

# 1. Create a sample student profile
sample_student = pd.Series({
    'quantitative_score': 85,
    'logical_score': 82,
    'verbal_score': 70,
    'creative_score': 65,
    'technical_score': 40,
    'aggregate_percentage': 88.0,
    'socio_economic_status': 'Middle',
    'school_type': 'Private',
    'parental_education': 'Graduate',
    'extracurricular': 'Sports',
    'state': 'Maharashtra',
    'prefers_government_college': 'Yes'
})

# 2. Define the feature list used for the admission model
admission_model_features = [
    'aggregate_percentage', 'score_cutoff_difference', 'socio_economic_status',
    'school_type', 'parental_education', 'extracurricular', 'state', 'college_state'
]

# Define college_df (from previous cells)
college_df = college_data.copy() # Ensure college_df is defined from the loaded data

# Corrected: Select the best models based on earlier evaluation
# stream_recommender_model was LightGBM for stream.
# admission_predictor_model was Random Forest for dropout (acting as admission here).
stream_recommender_model = models_stream["LightGBM"] # Re-confirming best stream model
admission_predictor_model = RandomForestClassifier(random_state=42).fit(X_train_adm_scaled, y_train_adm) # Re-instantiate and fit the best admission model


# 3. Run the engine!
top_colleges = get_college_recommendations(
    student_profile=sample_student,
    stream_model=stream_recommender_model,
    admission_model=admission_predictor_model,
    scaler=scaler_adm, # Now scaler_adm is defined
    train_cols=X_train_adm.columns,
    all_colleges_df=college_df,
    top_n=5
)

# 4. Print the final output
print("\nTop 5 Recommended Colleges for the Student:")
for i, (college, score) in enumerate(top_colleges, 1):
    print(f"{i}. {college} (Suitability Score: {score:.2f})")

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

# --- Final Step: Building the Holistic Recommendation Engine (Corrected) ---

# Re-assign your best models for clarity
stream_recommender_model = models_stream["LightGBM"] # From stream model training. Corrected to models_stream
admission_predictor_model = models["Random Forest"] # From admission model training. Corrected to Random Forest as it was better

# Create and fit a scaler specifically for the admission model data
scaler_adm = StandardScaler()
X_train_adm_scaled = scaler_adm.fit_transform(X_train_adm)
# Note: X_test_adm is not directly used here, but the scaler needs to be fitted.

def get_college_recommendations(student_profile, stream_model, admission_model, scaler, train_cols, all_colleges_df, top_n=5):
    """
    Generates a ranked list of the top N most suitable colleges for a student.
    ... (docstring remains the same)
    """

    print("---> Starting Recommendation Process ---")

    # --- Stage 1: Predict the Student's Best Stream ---
    # **CORRECTION IS HERE**: We define the list of columns correctly.
    aptitude_features = ['quantitative_score', 'logical_score', 'verbal_score', 'creative_score', 'technical_score']

    # We now select the data correctly, ensuring it's in the right format for the model
    student_aptitudes = student_profile[aptitude_features].values.reshape(1, -1)



    # Create a new scaler for stream prediction and fit it (assuming it's needed here as it was in stream training)
    stream_scaler = StandardScaler()
    stream_scaler.fit(X_stream) # X_stream is the full aptitude data used for stream model training
    student_aptitudes_scaled_for_stream = stream_scaler.transform(student_aptitudes)

    predicted_stream = stream_model.predict(student_aptitudes_scaled_for_stream)[0]
    print(f"1. Predicted Best Stream: {predicted_stream}")

    # --- Stage 2: Filter Colleges to Create a Candidate Pool ---
    candidate_colleges = all_colleges_df[all_colleges_df['stream_offered'].str.contains(predicted_stream, case=False, na=False)].copy()
    print(f"2. Found {len(candidate_colleges)} candidate colleges for this stream.")

    if candidate_colleges.empty:
        print("No colleges found for the predicted stream. Recommendation process stopped.")
        return []

    # --- Stage 3: Score and Rank Each Candidate College ---
    # (The rest of the function remains exactly the same)
    recommendations = []
    print("3. Scoring each candidate college...")

    for index, college in candidate_colleges.iterrows():
        prediction_data = student_profile.copy()
        prediction_data['college_state'] = college['college_state']
        prediction_data['last_year_cutoff'] = college['last_year_cutoff']
        prediction_data['score_cutoff_difference'] = prediction_data['aggregate_percentage'] - college['last_year_cutoff']

        single_row_df = pd.DataFrame([prediction_data.loc[admission_model_features]]) # Use .loc for Series indexing with list
        single_row_encoded = pd.get_dummies(single_row_df)
        single_row_aligned = single_row_encoded.reindex(columns=train_cols, fill_value=0)
        single_row_scaled = scaler.transform(single_row_aligned) # This `scaler` is `scaler_adm`

        admission_prob = admission_model.predict_proba(single_row_scaled)[0][1]
        academic_fit_score = admission_prob

        location_fit = 1.0 if student_profile['state'] == college['college_state'] else 0.5

        pref_fit = 0
        if student_profile['prefers_government_college'] == 'Yes' and 'Government' in college['college_type']:
            pref_fit = 1.0
        elif student_profile['prefers_government_college'] == 'No' and 'Private' in college['college_type']:
            pref_fit = 1.0

        personal_fit_score = np.mean([location_fit, pref_fit])

        final_score = (0.7 * academic_fit_score) + (0.3 * personal_fit_score)

        recommendations.append((college['college_name'], final_score))

    # --- Stage 4: Return the Top N Recommendations ---
    recommendations.sort(key=lambda x: x[1], reverse=True)

    print("\n--- Recommendation Process Complete ---")
    return recommendations[:top_n]


# --- DEMONSTRATION: HOW TO USE THE ENGINE ---

# 1. Create a sample student profile
sample_student = pd.Series({
    'quantitative_score': 85,
    'logical_score': 82,
    'verbal_score': 70,
    'creative_score': 65,
    'technical_score': 40,
    'aggregate_percentage': 88.0,
    'socio_economic_status': 'Middle',
    'school_type': 'Private',
    'parental_education': 'Graduate',
    'extracurricular': 'Sports',
    'state': 'Maharashtra',
    'prefers_government_college': 'Yes'
})

# 2. Define the feature list used for the admission model
admission_model_features = [
    'aggregate_percentage', 'score_cutoff_difference', 'socio_economic_status',
    'school_type', 'parental_education', 'extracurricular', 'state', 'college_state'
]

# Define college_df (from previous cells)
college_df = college_data.copy() # Ensure college_df is defined from the loaded data

# Corrected: Select the best models based on earlier evaluation
# stream_recommender_model was LightGBM for stream.
# admission_predictor_model was Random Forest for dropout (acting as admission here).
stream_recommender_model = models_stream["LightGBM"] # Re-confirming best stream model
admission_predictor_model = RandomForestClassifier(random_state=42).fit(X_train_adm_scaled, y_train_adm) # Re-instantiate and fit the best admission model


# 3. Run the engine!
top_colleges = get_college_recommendations(
    student_profile=sample_student,
    stream_model=stream_recommender_model,
    admission_model=admission_predictor_model,
    scaler=scaler_adm, # Now scaler_adm is defined
    train_cols=X_train_adm.columns,
    all_colleges_df=college_df,
    top_n=5
)

# 4. Print the final output
print("\nTop 5 Recommended Colleges for the Student:")
for i, (college, score) in enumerate(top_colleges, 1):
    print(f"{i}. {college} (Suitability Score: {score:.2f})")

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

# --- Final Step: Building the Holistic Recommendation Engine (Corrected) ---

# Re-assign your best models for clarity
stream_recommender_model = models_stream["LightGBM"] # From stream model training. Corrected to models_stream
admission_predictor_model = models["Random Forest"] # From admission model training. Corrected to Random Forest as it was better

# Create and fit a scaler specifically for the admission model data
scaler_adm = StandardScaler()
X_train_adm_scaled = scaler_adm.fit_transform(X_train_adm)
# Note: X_test_adm is not directly used here, but the scaler needs to be fitted.

def get_college_recommendations(student_profile, stream_model, admission_model, scaler, train_cols, all_colleges_df, top_n=5):
    """
    Generates a ranked list of the top N most suitable colleges for a student.
    ... (docstring remains the same)
    """

    print("---> Starting Recommendation Process ---")

    # --- Stage 1: Predict the Student's Best Stream ---
    # **CORRECTION IS HERE**: We define the list of columns correctly.
    aptitude_features = ['quantitative_score', 'logical_score', 'verbal_score', 'creative_score', 'technical_score']

    # We now select the data correctly, ensuring it's in the right format for the model
    student_aptitudes = student_profile[aptitude_features].values.reshape(1, -1)

    # Create a new scaler for stream prediction and fit it (assuming it's needed here as it was in stream training)
    stream_scaler = StandardScaler()
    stream_scaler.fit(X_stream) # X_stream is the full aptitude data used for stream model training
    student_aptitudes_scaled_for_stream = stream_scaler.transform(student_aptitudes)

    predicted_stream = stream_model.predict(student_aptitudes_scaled_for_stream)[0]
    print(f"1. Predicted Best Stream: {predicted_stream}")

    # --- Stage 2: Filter Colleges to Create a Candidate Pool ---
    # Corrected: Added regex=False to handle special characters in stream names like 'Science (PCB)'
    candidate_colleges = all_colleges_df[all_colleges_df['stream_offered'].str.contains(predicted_stream, case=False, na=False, regex=False)].copy()
    print(f"2. Found {len(candidate_colleges)} candidate colleges for this stream.")

    if candidate_colleges.empty:
        print("No colleges found for the predicted stream. Recommendation process stopped.")
        return []

    # --- Stage 3: Score and Rank Each Candidate College ---
    # (The rest of the function remains exactly the same)
    recommendations = []
    print("3. Scoring each candidate college...")

    for index, college in candidate_colleges.iterrows():
        prediction_data = student_profile.copy()
        prediction_data['college_state'] = college['college_state']
        prediction_data['last_year_cutoff'] = college['last_year_cutoff']
        prediction_data['score_cutoff_difference'] = prediction_data['aggregate_percentage'] - college['last_year_cutoff']

        single_row_df = pd.DataFrame([prediction_data.loc[admission_model_features]]) # Use .loc for Series indexing with list
        single_row_encoded = pd.get_dummies(single_row_df)
        single_row_aligned = single_row_encoded.reindex(columns=train_cols, fill_value=0)
        single_row_scaled = scaler.transform(single_row_aligned) # This `scaler` is `scaler_adm`

        admission_prob = admission_model.predict_proba(single_row_scaled)[0][1]
        academic_fit_score = admission_prob

        location_fit = 1.0 if student_profile['state'] == college['college_state'] else 0.5

        pref_fit = 0
        if student_profile['prefers_government_college'] == 'Yes' and 'Government' in college['college_type']:
            pref_fit = 1.0
        elif student_profile['prefers_government_college'] == 'No' and 'Private' in college['college_type']:
            pref_fit = 1.0

        personal_fit_score = np.mean([location_fit, pref_fit])

        final_score = (0.7 * academic_fit_score) + (0.3 * personal_fit_score)

        recommendations.append((college['college_name'], final_score))

    # --- Stage 4: Return the Top N Recommendations ---
    recommendations.sort(key=lambda x: x[1], reverse=True)

    print("\n--- Recommendation Process Complete ---")
    return recommendations[:top_n]


# --- DEMONSTRATION: HOW TO USE THE ENGINE ---

# 1. Create a sample student profile
sample_student = pd.Series({
    'quantitative_score': 85,
    'logical_score': 82,
    'verbal_score': 70,
    'creative_score': 65,
    'technical_score': 40,
    'aggregate_percentage': 88.0,
    'socio_economic_status': 'Middle',
    'school_type': 'Private',
    'parental_education': 'Graduate',
    'extracurricular': 'Sports',
    'state': 'Maharashtra',
    'prefers_government_college': 'Yes'
})

# 2. Define the feature list used for the admission model
admission_model_features = [
    'aggregate_percentage', 'score_cutoff_difference', 'socio_economic_status',
    'school_type', 'parental_education', 'extracurricular', 'state', 'college_state'
]

# Define college_df (from previous cells)
college_df = college_data.copy() # Ensure college_df is defined from the loaded data

# Corrected: Select the best models based on earlier evaluation
# stream_recommender_model was LightGBM for stream.
# admission_predictor_model was Random Forest for dropout (acting as admission here).
stream_recommender_model = models_stream["LightGBM"] # Re-confirming best stream model
admission_predictor_model = RandomForestClassifier(random_state=42).fit(X_train_adm_scaled, y_train_adm) # Re-instantiate and fit the best admission model


# 3. Run the engine!
top_colleges = get_college_recommendations(
    student_profile=sample_student,
    stream_model=stream_recommender_model,
    admission_model=admission_predictor_model,
    scaler=scaler_adm, # Now scaler_adm is defined
    train_cols=X_train_adm.columns,
    all_colleges_df=college_df,
    top_n=5
)

# 4. Print the final output
print("\nTop 5 Recommended Colleges for the Student:")
for i, (college, score) in enumerate(top_colleges, 1):
    print(f"{i}. {college} (Suitability Score: {score:.2f})")

import joblib

# Save stream recommender model with compression
joblib.dump(stream_recommender_model, "stream_model.pkl", compress=3)

# Save admission predictor model with compression
joblib.dump(admission_predictor_model, "admission_model.pkl",compress=3)

# Save scaler (important!)
joblib.dump(scaler_adm, "scaler.pkl",compress=3)

print("✅ Models saved successfully with compression!")





import os

# Get the file sizes
stream_model_size = os.path.getsize('stream_model.pkl')
admission_model_size = os.path.getsize('admission_model.pkl')
scaler_size = os.path.getsize('scaler.pkl')

print(f"Size of stream_model.pkl: {stream_model_size / (1024*1024):.2f} MB")
print(f"Size of admission_model.pkl: {admission_model_size / (1024*1024):.2f} MB")
print(f"Size of scaler.pkl: {scaler_size / (1024*1024):.2f} MB")

from google.colab import files
files.download("stream_model.pkl")
files.download("admission_model.pkl")
files.download("scaler.pkl")

model = joblib.load("stream_model.pkl")
model = joblib.load("admission_model.pkl")
model = joblib.load("scaler.pkl")
